GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjY4MTYwOTU5fQ.m_rgEhsNMjR-W-Twolk7hfapz6g8DDnlSEMcXuTre0c


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Jim"
}